### ISSUE TITLE
Scss lint trows an error

### ISSUE THREAD

**Issue by vedran-milic** [juanfran/gulp-scss-lint#45]
When I run gulp lint i get this error.
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Configuration error

My task looks like this.
gulp.task('lint', function() {
  gulp.src('scss/**/*.scss')
    .pipe(scsslint({
      'config': 'scss-lint.yml',
    }));
});

node version 0.12.7
npm version 2.13.2

**Comment by juanfran** [comment]
your `scss-lint.yml` file should have an error, if you copy it here I will help you.

**Comment by vedran-milic** [comment]
Here it is.

linters:
  Comment:
    enabled: false

  NestingDepth:
    enabled: true
    max_depth: 6

  SelectorDepth:
    enabled: true
    max_depth: 6

**Comment by juanfran** [comment]
this works for me, with the spaces. Check also the `scss-lint.yml` path. It should be in the same directory as the gulpfile.js

``` yml
linters:
  Comment:
    enabled: false

  NestingDepth:
    enabled: true
    max_depth: 6

  SelectorDepth:
    enabled: true
    max_depth: 6
```
If it doesn't work add the `verbose` option and run the output command because maybe it could be a ruby scss-lint problem.
